project:
  type: website
  output-dir: ../docs

website:
  title: "FlowerForest"
  navbar:
    left:
      - href: index.qmd
        text: ç›®å½•é¦–é¡µ
      - href: about.qmd
      - text: æˆ‘çš„ä½œå“
        menu:
          - href: posts/flower-forest.qmd
            text: ğŸŒ¸ é²œèŠ±ç››æ—¶çš„æ£®æ—
          - href: plus/index.qmd
            text: ğŸ“š å€’è®¡æ—¶ä¸ºè´Ÿçš„ä¸‰ç™¾å…­åäº”ä¸ªæ—¥æœˆï¼ˆæ€»ç›®å½•ï¼‰

format:
  html:
    theme: cosmo
    toc: true

